Revert "Build(deps): Bump redis from 4.2.2 to 4.2.3" (#11279)
This reverts commit 2e851b62b025520d70e36adb3b0a2821c13f696c.

This is causing `NoMethodError (undefined method `bytesize' for nil:NilClass)` in the anonymous cache. More investigation required